
<div class="card text-center">
    <div class="card-header">
        Contact us
    </div>
    <div class="card-body">
        <h5 class="card-title">Contact us now</h5>
        <p class="card-text">For help and enquiries, contact us here.</p>
        <a href="mailto:d.thomas18@edu.salford.ac.uk" class="btn btn-primary">Send us a message</a>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
