<footer class="mt-4">
    <div class="card text-center">
        <div class="card-header">
            Contact us
        </div>
        <div class="card-body">
            <h5 class="card-title">Contact us now</h5>
            <p class="card-text">For help and enquiries, contact us here.</p>
            <a href="mailto:d.thomas18@edu.salford.ac.uk" class="btn btn-primary">Send us a message</a>
        </div>
    </div>
</footer>
<footer class="bg-dark text-white py-4 mt-5">
    <div class="container text-center">
        <p>&copy; Terms and conditions.</p>
    </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>