<?php require_once('template/header.phtml'); ?>

    <body>
<div class="container mt-3">
    <h1>
        Account
    </h1>
    <h2>
        Welcome <?php echo $_SESSION['name']; ?>
    </h2>
    <!-- Smaller Box -->
    <div class="container mt-3 border rounded bg-white p-3" style="max-width: 600px;">
        <a><?php if ($_SESSION['userType'] == 2) {
                echo "Student";
            } elseif ($_SESSION['userType'] == 3) {
                echo "Employer";
            } else {
                echo "Admin";
            } ?> Account</a>
        <h5 class="mt-2">Email</h5>
        <p class="border p-2"><?php echo $_SESSION['email']; ?></p>
        <?php if (!empty($view->userInfoDataSet)): ?>
            <h5 class="mt-2">Address</h5>
            <p class="border p-2"><?php echo $view->userInfoDataSet->getAddress(); ?></p>
            <h5 class="mt-2">Phone Number</h5>
            <p class="border p-2"><?php echo $view->userInfoDataSet->getPhoneNumber(); ?></p>
            <h5 class="mt-2">Date Of Birth (YY-MM-DD)</h5>
            <p class="border p-2"><?php echo $view->userInfoDataSet->getDobYMD(); ?></p>
        <?php endif; ?>
        <?php if (!empty($view->studentInfoDataSet)): ?>
            <h5 class="mt-2">Address</h5>
            <p class="border p-2"><?php echo $view->userInfoDataSet->getAddress(); ?></p>
        <?php endif; ?>
    </div>
</div>

<!-- Larger Edit Button -->
<div id="editButtonContainer" class="text-end me-3">
    <button type="button" class="btn btn-primary"
            style="--bs-btn-padding-y: 1rem; --bs-btn-padding-x: 2rem; --bs-btn-font-size: 1.25rem;">
        <i class="fas fa-edit"></i> Edit
    </button>
</div>

<?php require_once("template/footer.phtml"); ?>