<?php require_once('template/header.phtml'); ?>

<body>
<div class="container mt-3">
    <h1>
        Account
    </h1>
    <h2>
        Welcome <?php echo $_SESSION['name'];?>
    </h2>
    <div class="container mt-3 border rounded bg-white p-3">
        <a ><?php if($_SESSION['userType'] == 2){echo "Student";} elseif($_SESSION['userType'] == 3){echo "Employer";} else{echo "Admin";} ?> Account</a>
        <h5 class="mt-2">Email</h5>
        <p class="border p-2"><?php echo $_SESSION['email'];?></p>
        <h5 class="mt-2">Address</h5>
        <p class="border p-2"><?php echo $view->userInfoDataSet;?></p>
    </div>
</div>
</body>

<?php require_once ("template/footer.phtml"); ?>