<?php require_once ("template/header.phtml"); ?>

    <div class="d-flex flex-column min-vh-100">
        <!-- Main Content -->
        <div class="flex-grow-1 d-flex justify-content-center align-items-center">
            <div class="col-md-4"> <!-- Centered and limited width -->
                <form action="../Controller/login.php" method="post" class="px-4 py-3">
                    <div class="mb-3">
                        <label for="usernameOrEmail" class="form-label">Username or Email address</label>
                        <input type="text" class="form-control" id="usernameOrEmail" name="email" placeholder="Username or Email" required>
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Password</label>
                        <input type="password" class="form-control" id="password" name="password" placeholder="Password" required>
                    </div>
                    <div class="mb-2 form-check">
                        <input type="checkbox" class="form-check-input" id="rememberMe" name="remember_me">
                        <label class="form-check-label" for="rememberMe">Remember me</label>
                    </div>
                    <a class="errorMessage"><?php echo isset($view->errorMessage) ? htmlspecialchars($view->errorMessage) : '';  ?></a>
                    <button type="submit" class="btn btn-primary w-100">Sign In</button>
                </form>
                <div class="dropdown-divider"></div>
                <p class="mt-3 text-center">
                    New around here? <a href="../Controller/registerPage1.php">Sign up</a>
                </p>
            </div>
        </div>
    </div>

    <!-- Footer -->
<?php require_once ("template/footer.phtml"); ?>