<?php require_once ("template/header.phtml"); ?>
    <div class="col-md-9">
        <h5 class="mb-3">Added placements</h5>
        <ul class="list-group">
            <?php if (isset($view->jobListData)): ?>
                <?php foreach ($view->jobListData as $job): ?>
                    <li class="list-group-item p-3 mb-3 yellow-card-job-list">
                        <h5 class="mb-2"><?= htmlspecialchars($job->getTitle()); ?></h5>
                        <p class="text-muted mb-1"><?= htmlspecialchars($job->getDescription()); ?></p>
                        <p class="mb-1"><strong>Salary:</strong> <?= htmlspecialchars($job->getSalary()); ?></p>
                        <p class="mb-1"><strong>Location:</strong> <?= htmlspecialchars($job->getLocation()); ?></p>
                        <p class="mb-1"><strong>Skills Required:</strong> <?= htmlspecialchars($view->skill[$job->getSkills()]); ?></p>
                        <p class="mb-1"><strong>Start Date:</strong> <?= htmlspecialchars($job->getStartDate()); ?></p>
                        <p class="mb-1"><strong>End Date:</strong> <?= htmlspecialchars($job->getEndDate()); ?></p>
                        <a href="../Controller/myListings.php" class="btn btn-primary btn-sm mt-2">Apply</a>
                    </li>
                <?php endforeach; ?>
            <?php endif; ?>
        </ul>
    </div>



<?php require_once ("template/footer.phtml"); ?>