<?php require_once('template/header.phtml'); ?>
<div class="container-fluid d-flex flex-column min-vh-100">
    <div class="flex-grow-1 d-flex justify-content-center align-items-center">
        <form class="row g-3 w-100" style="max-width: 600px;" action="../Controller/registerPage1.php" method="POST">
            <div class="col-md-6">
                <label for="validationServer01" class="form-label">First name</label>
                <input type="text" class="form-control" id="validationServer01" name="first_name" required>
                <div class="valid-feedback">
                    Looks good!
                </div>
            </div>
            <div class="col-md-6">
                <label for="validationServer02" class="form-label">Last name</label>
                <input type="text" class="form-control" id="validationServer02" name="last_name" required>
                <div class="valid-feedback">
                    Looks good!
                </div>
            </div>
            <div class="col-md-12">
                <label for="validationServer03" class="form-label">Email Address</label>
                <input type="email" class="form-control" id="validationServer03" name="email" required>
                <div class="valid-feedback">
                    Looks good!
                </div>
            </div>
            <div class="col-md-6">
                <label for="validationServer04" class="form-label">Date of Birth</label>
                <input type="date" class="form-control" id="validationServer04" name="dob" required>
                <div class="valid-feedback">
                    Looks good!
                </div>
            </div>
            <div class="col-md-6">
                <label for="validationServer05" class="form-label">Phone Number</label>
                <input type="tel" class="form-control" id="validationServer05" name="phone" required>
                <div class="valid-feedback">
                    Looks good!
                </div>
            </div>
            <div class="col-md-6">
                <label for="validationServer06" class="form-label">Username</label>
                <input type="text" class="form-control" id="validationServer06" name="username" required>
                <div class="valid-feedback">
                    Looks good!
                </div>
            </div>
            <div class="col-md-6">
                <label for="validationServer07" class="form-label">Password</label>
                <input type="password" class="form-control" id="validationServer07" name="password" required>
                <div class="valid-feedback">
                    Looks good!
                </div>
            </div>
            <div class="col-md-12">
                <label class="form-label">User Type</label>
                <div class="d-flex justify-content-start align-items-center">
                    <div class="form-check me-3">
                        <input type="radio" id="student" name="user_type" value="student" class="form-check-input" required>
                        <label for="student" class="form-check-label">Student</label>
                    </div>
                    <div class="form-check">
                        <input type="radio" id="employer" name="user_type" value="employer" class="form-check-input" required>
                        <label for="employer" class="form-check-label">Employer</label>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <button class="btn btn-primary w-100" type="submit">Submit form</button>
            </div>
        </form>
    </div>
</div>

<?php require_once('template/footer.phtml'); ?>
