<?php require_once("template/header.phtml"); ?>
    <h1>Applicants for placements</h1>
<?php if (!empty($applicants)): ?>
    <table class="table table-bordered">
        <thead class="table-light">
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Phone Number</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($applicants as $applicant): ?>
            <tr>
                <td><?= htmlspecialchars($applicant['firstName']); ?></td>
                <td><?= htmlspecialchars($applicant['lastName']); ?></td>
                <td><?= htmlspecialchars($applicant['email']); ?></td>
                <td><?= htmlspecialchars($applicant['phone']); ?></td>
                <td>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <p class="text-muted">No applicants found for this placement.</p>
<?php endif; ?>

<?php require_once("template/footer.phtml"); ?>